config/routes.rb
Rails.application.routes.draw do
  resources :categories
    namespace :admin do
        devise_scope :user do
            get 'invitation', to: 'invitations#new'
        end
        resources :users, only: [:index]
        resources :invites, only: [:index]
        resources :companies, except: [:show]
    end

    devise_for :users, :controllers => {:registrations => "registrations", invitations: 'invitations'}
    root to: "pages#index"
    resources :pages
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :models
  belongs_to :company
  enum role: {user: 0, publisher: 1, admin: 2}
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # include DeviseInvitable::Inviter
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  
  before_action :authenticate_user!

  layout "admin"

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  def index
    @companies = Company.all
    authorize @companies
  end

  def new
    @company = Company.new
    authorize @company
  end

  def edit
    authorize @company
  end

  def create
    @company = Company.new(company_params)

      if @company.save
        redirect_to admin_companies_url, notice: "Company was successfully created."
      else
        render :new, status: :unprocessable_entity 
      end
  end

  def update
      if @company.update(company_params)
        redirect_to admin_companies_url, notice: "Company was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    authorize @company
    @company.destroy
    

      redirect_to admin_companies_url, notice: "Company was successfully destroyed."
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < Devise::InvitationsController
    before_action :configure_permitted_parameters
    before_action :authenticate_user!
    
layout "admin"



    def new
      authorize User
      super
    end
     protected

  # Permit the new params here.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite, keys: [:role])
  end

end

app/controllers/admin/invites_controller.rb
class Admin::InvitesController < Admin::ApplicationController
    

    def index
        @pending_users = User.where.not(invitation_token: nil)
        authorize @pending_users
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
    
    def index
        
        @users = User.where(invitation_token: nil)
        authorize @users
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


    # layout :choose_layout

    # protected
    #   def choose_layout
    #     if current_user.nil?
    #       'application'
    #     elsif current_user.admin?
    #         'admin'
    #     else
    #       'application'
    #     end
    #   end
 
  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  # def authenticate_inviter!
  #   unless current_user.role=="admin"
  #     redirect_to root_url, :alert => "Access Denied"
  #   end
  #   super
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

      if @category.save
        redirect_to category_url(@category), notice: "Category was successfully created." 
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        redirect_to category_url(@category), notice: "Category was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :title, :description)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < Devise::InvitationsController
    before_action :configure_permitted_parameters
    before_action :authenticate_user!
    
#  layout :set_layout


    def new
    redirect_to admin_invitation_path and return
    super
    end
     protected

  # Permit the new params here.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:first_name, :last_name, :company_id])
  end

  # def set_layout
  #   if current_user.nil?
  #     'application'
  #   elsif current_user.admin?
  #       'admin'
  #   else
  #     'application'
  #   end
  # end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.fetch(:page, {})
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # def new
  #   redirect_to new_user_session_path and return
  #   super
  # end

    protected
  

    def after_sign_up_path_for(resource)
      root_path # Or :prefix_to_your_route
    end
  end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/companies/_form.html.erb
<div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="w-full max-w-md space-y-8">

    <%= form_with(model: [:admin, company]) do |form| %>
     <% if company.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

        <ul>
          <% company.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
      <input type="hidden" name="remember" value="true">
      <div class="-space-y-px rounded-md shadow-sm">

        <div>
          <%= form.label :name, "Company name", class: "sr-only" %>
          <%= form.text_field :name, autofocus: true, autocomplete: "Company name", required: true, class: "relative block w-full appearance-none rounded-none rounded-t-md rounded-b-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm", placeholder: "Company name" %>
        </div>
      </div>

        <div>
              <%= form.submit "Save", class: "group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
        </div>

        <div class="mt-4">
          <%= link_to "Back to companies", admin_companies_path, class: "group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"  %>
        </div>
    <% end %>
  </div>
</div>

app/views/admin/companies/edit.html.erb
<%= render "form", company: @company %>

app/views/admin/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<section class="antialiased bg-gray-100 text-gray-600 h-screen px-4">
  <div class="flex flex-col justify-start h-full">
    <!-- Table -->
      <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
        <header class="px-5 py-4 border-b border-gray-100">
          <div class="flex justify-between ">
            <h2 class="font-semibold text-gray-800">Companies:</h2>
            <%= link_to "New company", new_admin_company_path, class: "group relative  justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          </div>
        </header>
          <div class="p-3">
            <div class="overflow-xauto">
              <table class="table-auto w-full">
                <thead class="text-xs font-semibold uppercase text-gray-400 bg-gray-50">
                  <tr>
                    <th class="p-2 whitespace-nowrap font-semibold text-left">ID</th>
                    <th class="p-2 whitespace-nowrap font-semibold text-left">Name</th>
                    <th class="p-2 whitespace-nowrap font-semibold text-center">Action</th>
                  </tr>
                </thead>

                <tbody class="text-sm divide-y divide-gray-100">
                  <% @companies.each do |company| %>
                    <tr>
                      <td class="p-2 whitespace-nowrap font-medium text-gray-800"><%= company.id %></td>
                      <td class="p-2 whitespace-nowrap text-left"><%= company.name %></td>
                      <td class="p-2 whitespace-nowrap text-lg text-center">
                        <div class="flex justify-center">
                          <%= link_to "Edit", edit_admin_company_path(company), class: "group relative  justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %> |
                          <%= button_to "Destroy", [:admin, company], method: :delete, class: "group relative  justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
      </div>
  </div>
</section>

app/views/admin/companies/new.html.erb
<%= render "form", company: @company %>

app/views/admin/companis/_form.html.erb
<div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="w-full max-w-md space-y-8">

    <%= form_with(model: [:admin, compani]) do |form| %>
     <% if compani.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(compani.errors.count, "error") %> prohibited this compani from being saved:</h2>

        <ul>
          <% compani.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
      <input type="hidden" name="remember" value="true">
      <div class="-space-y-px rounded-md shadow-sm">

        <div>
          <%= form.label :companiname, "Company name", class: "sr-only" %>
          <%= form.text_field :companiname, autofocus: true, autocomplete: "Company name", required: true, class: "relative block w-full appearance-none rounded-none rounded-t-md rounded-b-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm", placeholder: "Company name" %>
        </div>
      </div>

        <div>
              <%= form.submit "Save", class: "group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
        </div>

        <div class="mt-4">
          <%= link_to "Back to companis", admin_companis_path, class: "group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"  %>
        </div>
    <% end %>
  </div>
</div>

app/views/admin/companis/index.html.erb
<p style="color: green"><%= notice %></p>

<section class="antialiased bg-gray-100 text-gray-600 h-screen px-4">
  <div class="flex flex-col justify-start h-full">
    <!-- Table -->
      <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
        <header class="px-5 py-4 border-b border-gray-100">
          <div class="flex justify-between ">
            <h2 class="font-semibold text-gray-800">Companis:</h2>
            <%= link_to "New compani", new_admin_compani_path, class: "group relative  justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          </div>
        </header>
          <div class="p-3">
            <div class="overflow-xauto">
              <table class="table-auto w-full">
                <thead class="text-xs font-semibold uppercase text-gray-400 bg-gray-50">
                  <tr>
                    <th class="p-2 whitespace-nowrap font-semibold text-left">ID</th>
                    <th class="p-2 whitespace-nowrap font-semibold text-left">Name</th>
                    <th class="p-2 whitespace-nowrap font-semibold text-center">Action</th>
                  </tr>
                </thead>

                <tbody class="text-sm divide-y divide-gray-100">
                  <% @companis.each do |compani| %>
                    <tr>
                      <td class="p-2 whitespace-nowrap font-medium text-gray-800"><%= compani.id %></td>
                      <td class="p-2 whitespace-nowrap text-left"><%= compani.companiname %></td>
                      <td class="p-2 whitespace-nowrap text-lg text-center">
                        <div class="flex justify-center">
                          <%= link_to "Edit", edit_admin_compani_path(compani), class: "group relative  justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %> |
                          <%= button_to "Destroy", [:admin, compani], method: :delete, class: "group relative  justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
      </div>
  </div>
</section>

app/views/admin/invites/index.html.erb
<section class="antialiased bg-gray-100 text-gray-600 h-screen px-4">
  <div class="flex flex-col justify-start h-full">
    <!-- Table -->
      <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
        <header class="px-5 py-4 border-b border-gray-100">
          <h2 class="font-semibold text-gray-800">list of pending users:</h2>
        </header>
          <div class="p-3">
            <div class="overflow-x-auto">
              <table class="users table-auto w-full">
                <thead class="text-xs font-semibold uppercase text-gray-400 bg-gray-50">
                  <tr>
                    <th>ID</th>
                    <th>Email</th>
                    <th>Role</th>
                  </tr>
                </thead>

                <tbody class="text-sm divide-y divide-gray-100">
                  <% @pending_users.each do |user| %>
                    <tr>
                      <td class="font-medium text-gray-800"><%= user.id %></td>
                      <td class="text-left"><%= user.email %></td>
                      <td class="text-left font-medium text-green-500"><%= user.role %></div></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
      </div>
  </div>
</section>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Navigator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

<div class="min-h-full">
  <nav class="bg-green-500">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

              <% if user_signed_in? %>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%# <%= link_to "Edit User", edit_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                  
                  <%# <% if current_user.admin? %>
                  <% if policy([:user]).index? %>
                    <%= link_to "Users", admin_users_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                    <%= link_to "Pending Users", admin_invites_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                  <% end %>

                  <% if policy([:user]).new? %>
                    <%= link_to "Invite User", admin_invitation_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                  <% end %>

                  <% if policy([:company]).index? %>
                    <%= link_to "Companies", admin_companies_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                  <% end %>
               <%= link_to "User panel", root_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>



              <% else %>
                <%= link_to "Sign in", user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%# <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden" id="mobile-menu">
      <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <% if user_signed_in? %>
                <%= button_to "Вихід", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                <%# <%= link_to "Редагувати", edit_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %> 
              <% else %>
                <%= link_to "Вхід", user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                <%# <%= link_to "Реєстрація", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
              <% end %>

      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Navigator</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

       <%= yield %>
  </main>
</div>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Navigator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

<div class="min-h-full">
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

              <% if user_signed_in? %>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%# <%= link_to "Edit User", edit_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <% if policy([:user]).index? %>
                  <%= link_to "Admin panel", admin_users_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <% end %>


              <% else %>
                <%= link_to "Sign in", user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
                <%# <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden" id="mobile-menu">
      <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <% if user_signed_in? %>
                <%= button_to "Вихід", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                <%# <%= link_to "Редагувати", edit_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %> 
              <% else %>
                <%= link_to "Вхід", user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
                <%# <%= link_to "Реєстрація", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
              <% end %>

      </div>
    </div>
  </nav>

  <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Navigator</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

       <%= yield %>
  </main>
</div>


  </body>
</html>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>